---

- name: create redis dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    recurse: true
  changed_when: false
  with_items:
    - "{{ redis_server_opt_dir }}"
    - "{{ redis_server_log_dir }}"
    - "{{ redis_server_config_dir }}"
    - "{{ redis_server_data_dir }}"

- name: create redis configuration file
  template:
    dest: "{{ redis_server_config_dir }}/{{ item | basename }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    src: "{{ item }}"
  with_items:
    - config/redis_server.conf
  register: config_change
