---

- name: Copy redis script
  ansible.builtin.template:
    src: "redis"
    dest: /usr/local/bin/redis
    mode: 0755
    owner: root
    group: root

- name: Copy redis script
  ansible.builtin.template:
    src: "redis.service"
    dest: /etc/systemd/system/redis.service
    mode: 0644
    owner: root
    group: root

- name: Install redis tools
  ansible.builtin.apt:
    name: Redis-tools
    state: present
    update_cache: true

- name: Restart redis service is restarted
  ansible.builtin.service:
    name: Redis
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for redis to become ready
  ansible.builtin.wait_for:
    host: "{{ redis_server_bind }}"
    port: "{{ redis_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
