---

- name: Setup group
  ansible.builtin.group:
     name: "{{ redis_group }}"
     system: false

- name: Setup user
  ansible.builtin.user:
     name: "{{ redis_user }}"
     system: false
     group: "{{ redis_group }}"
