---
# handlers for ansible-role-docker-redis

- name: restart redis
  service:
    name: redis
    state: restarted
    enabled: true

- name: start redis
  service:
    name: redis
    state: started
    enabled: true

- name: reload redis
  service:
    name: redis
    state: reloaded
    enabled: true