---
# handlers for ansible-role-docker-redis

- name: Restart redis
  ansible.builtin.service:
    name: Redis
    state: restarted
    enabled: true

- name: Start redis
  ansible.builtin.service:
    name: Redis
    state: started
    enabled: true

- name: Reload redis
  ansible.builtin.service:
    name: Redis
    state: reloaded
    enabled: true
